"""Lookup tables mapping human-readable names to TMDB identifiers.

Seeded with the most common providers/countries/genres. Populate further from
TMDB's live endpoints if needed:

  * Providers: GET /watch/providers/movie?watch_region={CC}
  * Regions:   GET /watch/providers/regions
  * Genres:    GET /genre/movie/list
"""
from __future__ import annotations

# Common alternate spellings/aliases users type for a platform whose TMDB
# display name differs (e.g. the app's own example prompt suggests "Disney+",
# but PLATFORM_TO_PROVIDER_ID's key is "Disney Plus") -> the canonical key in
# PLATFORM_TO_PROVIDER_ID. Lookups in resolve_provider_ids are case-insensitive
# and check this map before giving up.
PLATFORM_NAME_ALIASES = {
    "disney+": "Disney Plus",
    "disney plus": "Disney Plus",
    "apple tv+": "Apple TV Plus",
    "prime video": "Amazon Prime Video",
    "amazon prime": "Amazon Prime Video",
    "hbo max": "HBO Max",
    "max": "HBO Max",
    "paramount+": "Paramount Plus",
    "peacock": "Peacock Premium",
}

# Maps a streaming platform display name -> TMDB provider ID.
PLATFORM_TO_PROVIDER_ID = {
    "Apple TV": 2,
    "Google Play Movies": 3,
    "Vudu": 7,
    "Netflix": 8,
    "Amazon Prime Video": 119,  # Last occurrence in dict keys overrides 9
    "Amazon Video": 10,
    "MUBI": 11,
    "Crackle": 12,
    "realeyz": 14,
    "Hulu": 15,
    "NetMovies": 19,
    "maxdome Store": 20,
    "Stan": 21,
    "Quickflix": 22,
    "Quickflix Store": 24,
    "Fandor": 25,
    "Netzkino": 28,
    "Sky Go": 29,
    "WOW": 30,
    "Alleskino": 33,
    "MGM Plus": 34,
    "Rakuten TV": 35,
    "Showtime": 37,
    "BBC iPlayer": 38,
    "Now TV": 39,
    "Chili": 40,
    "ITVX": 41,
    "Starz": 43,
    "Looke": 47,
    "Volta": 53,
    "BoxOffice": 54,
    "ShowMax": 55,
    "OCS Go": 56,
    "Canal VOD": 58,
    "Bbox VOD": 59,
    "Orange VOD": 61,
    "Atres Player": 62,
    "Filmin": 63,
    "Filmin Plus": 64,
    "Filmin Latino": 66,
    "Blim": 67,
    "Microsoft Store": 68,
    "Pathé Thuis": 71,
    "Videoland": 72,
    "Tubi TV": 73,
    "Viaplay": 76,
    "C More": 77,
    "CBS": 78,
    "tenplay": 82,
    "The CW": 83,
    "U-NEXT": 84,
    "dTV": 85,
    "Acorn TV": 87,
    "Kividoo": 89,
    "Naver Store": 96,
    "Watcha": 97,
    "Shudder": 99,
    "GuideDoc": 100,
    "All 4": 103,
    "Timvision": 109,
    "Infinity+": 110,
    "Ivi": 113,
    "Okko": 115,
    "Amediateka": 116,
    "Kinopoisk": 117,
    "HBO": 118,
    "Voot": 121,
    "Hotstar": 122,
    "FXNow": 123,
    "Bookmyshow": 124,
    "Sky Store": 130,
    "SBS On Demand": 132,
    "Videobuster": 133,
    "Foxtel Now": 134,
    "ABC iview": 135,
    "FILMO": 138,
    "Cineplex": 140,
    "Sundance Now": 143,
    "iciTouTV": 146,
    "Sixplay": 147,
    "ABC": 148,
    "Movistar Plus": 149,
    "blue TV": 150,
    "BritBox": 380,  # Last occurrence in dict keys overrides 151
    "Lifetime": 157,
    "Viu": 158,
    "Catchplay": 159,
    "iflix": 160,
    "Hollystar": 164,
    "Claro video": 167,
    "Watchbox": 171,
    "Netflix Kids": 175,
    "Pantaflix": 177,
    "MagentaTV": 178,
    "Hollywood Suite": 182,
    "Universal Pictures": 184,
    "Screambox": 185,
    "YouTube Premium": 188,
    "Curzon Home Cinema": 189,
    "Curiosity Stream": 190,
    "Kanopy": 191,
    "YouTube": 192,
    "Starz Play Amazon Channel": 194,
    "Animax Plus Amazon Channel": 195,
    "AcornTV Amazon Channel": 196,
    "BritBox Amazon Channel": 197,
    "Fandor Amazon Channel": 199,
    "MUBI Amazon Channel": 201,
    "Screambox Amazon Channel": 202,
    "Showtime Amazon Channel": 203,
    "Shudder Amazon Channel": 204,
    "Sundance Now Amazon Channel": 205,
    "The Roku Channel": 207,
    "PBS": 209,
    "Sky": 210,
    "Freeform": 211,
    "Hoopla": 212,
    "Syfy": 215,
    "Eros Now": 218,
    "Das Erste Mediathek": 219,
    "Jio Cinema": 220,
    "Rai Play": 222,
    "BFI Player": 224,
    "Telecine Play": 227,
    "Crave": 230,
    "Zee5": 232,
    "Arte": 234,
    "YouTube Free": 235,
    "France TV": 236,
    "Sony Liv": 237,
    "Universcine": 239,
    "Popcornflix": 241,
    "Meo": 242,
    "Comedy Central": 243,
    "HBO Poland": 244,
    "VOD Poland": 245,
    "7plus": 246,
    "Pantaya": 247,
    "Boomerang": 248,
    "Horizon": 250,
    "Urban Movie Channel": 251,
    "Dove Channel": 254,
    "Yupp TV": 255,
    "fuboTV": 257,
    "Criterion Channel": 258,
    "Magnolia Selects": 259,
    "WWE Network": 260,
    "Nickhits Amazon Channel": 261,
    "Noggin Amazon Channel": 262,
    "History Vault": 268,
    "Funimation Now": 269,
    "Neon TV": 273,
    "QubitTV": 274,
    "Laugh Out Loud": 275,
    "Smithsonian Channel": 276,
    "Pure Flix": 278,
    "Redbox": 279,
    "Hallmark Movies": 281,
    "Crunchyroll": 283,
    "Lifetime Movie Club": 284,
    "BBC Player Amazon Channel": 285,
    "ZDF Herzkino Amazon Channel": 286,
    "BFI Player Amazon Channel": 287,
    "Boomerang Amazon Channel": 288,
    "Cinemax Amazon Channel": 289,
    "Hallmark Movies Now Amazon Channel": 290,
    "MZ Choice Amazon Channel": 291,
    "PBS Kids Amazon Channel": 293,
    "PBS Masterpiece Amazon Channel": 294,
    "Viewster Amazon Channel": 295,
    "Ziggo TV": 297,
    "RTL+": 298,
    "Sling TV Orange and Blue": 299,
    "Pluto TV": 300,
    "Joyn": 304,
    "Crave Starz": 305,
    "Globoplay": 307,
    "O2 TV": 308,
    "Sun Nxt": 309,
    "LaCinetek": 310,
    "Be TV Go": 311,
    "VRT MAX": 312,
    "Yelo Play": 313,
    "CBC Gem": 314,
    "Hoichoi": 315,
    "Alt Balaji": 319,
    "Sky X": 321,
    "USA Network": 322,
    "Yle Areena": 323,
    "Cinemas a la Demande": 324,
    "CTV": 326,
    "FlixFling": 331,
    "VUDU Free": 332,
    "My5": 333,
    "Filmtastic Amazon Channel": 334,
    "Disney Plus": 390,  # Last occurrence in dict keys overrides 337
    "Ruutu": 338,
    "Movistar Play": 339,
    "blutv": 341,
    "puhutv": 342,
    "Bet+ Amazon Channel": 343,
    "Rakuten Viki": 344,
    "Kino on Demand": 349,
    "Apple TV Plus": 350,
    "AMC on Demand": 352,
    "WAKANIM": 354,
    "Darkmatter TV": 355,
    "wavve": 356,
    "DocPlay": 357,
    "DIRECTV": 358,
    "Mediaset Infinity": 359,
    "NPO Start": 360,
    "TCM": 361,
    "TNT": 363,
    "IndieFlix": 368,
    "VOD Club": 370,
    "Go3": 373,
    "Hotstar Disney+": 377,
    "Canal+": 381,
    "TV 2": 383,
    "HBO Max": 384,
    "BINGE": 385,
    "Peacock": 386,
    "Peacock Premium": 387,
    "Sooner": 389,
    "wedotv": 392,
    "FlixOlé": 393,
    "TVNZ": 395,
    "Film1": 396,
    "BBC America": 397,
    "VVVVID": 414,
    "Anime Digital Networks": 415,
    "Here TV": 417,
    "Joyn Plus": 421,
    "Blockbuster": 423,
    "HBO Go": 425,
    "SF Anytime": 426,
    "CONtv": 428,
    "Telstra TV": 429,
    "HiDive": 430,
    "TV 2 Play": 431,
    "Flix Premiere": 432,
    "OVID": 433,
    "OzFlix": 434,
    "Draken Films": 435,
    "Fetch TV": 436,
    "Hungama Play": 437,
    "Chai Flicks": 438,
    "Shout! Factory TV": 439,
    "ThreeNow": 440,
    "NFB": 441,
    "NRK TV": 442,
    "Filmstriben": 443,
    "Dekkoo": 444,
    "Classix": 445,
    "Retrocrush": 446,
    "Belas Artes à La Carte": 447,
    "Beamafilm": 448,
    "Global TV": 449,
    "Vodacom Video Play": 450,
    "Picl": 451,
    "RTPplay": 452,
    "Topic": 454,
    "Night Flight Plus": 455,
    "Mitele ": 456,
    "VIX ": 457,
    "Horrify": 460,
    "RTBF": 461,
    "Kirjastokino": 463,
    "Kocowa": 464,
    "Believe": 465,
    "Bioskop Online": 466,
    "DIRECTV GO": 467,
    "genflix": 468,
    "Club Illico": 469,
    "The Film Detective": 470,
    "FILMRISE": 471,
    "NLZIET": 472,
    "Revry": 473,
    "ShemarooMe": 474,
    "DOCSVILLE": 475,
    "EPIC ON": 476,
    "GOSPEL PLAY": 477,
    "History Play": 478,
    "Home of Horror": 479,
    "Filmtastic": 480,
    "ArthouseCNMA": 481,
    "ManoramaMax": 482,
    "MAX Stream": 483,
    "NOW": 484,
    "Spectrum On Demand": 486,
    "tvo": 488,
    "Vidio": 489,
    "CINE": 491,
    "SVT": 493,
    "Cineasterna": 496,
    "Tele2 Play": 497,
    "Oldflix": 499,
    "TVF Play": 500,
    "Wink": 501,
    "Tata Play": 502,
    "Hi-YAH": 503,
    "VRV": 504,
    "Player": 505,
    "TBS": 506,
    "tru TV": 507,
    "Discovery Plus": 524,  # Last occurrence in dict keys overrides 510, 520
    "iWantTFC": 511,
    "TNTGo": 512,
    "Shadowz": 513,
    "AsianCrush": 514,
    "MX Player": 515,
    "Noovo": 516,
    "TriArt Play": 517,
    "La Toile": 518,
    "Spamflix": 521,
    "Popcorntimes": 522,
    "Knowledge Network": 525,
    "AMC+": 526,
    "AMC+ Amazon Channel": 528,
    "ARROW": 529,
    "Supo Mungam Plus": 530,
    "Paramount Plus": 531,
    "aha": 532,
    "Amazon Arthaus Channel": 533,
    "Argo": 534,
    "digital TIFF Bell Lightbox": 535,
    "Dogwoof On Demand": 536,
    "ZDF": 537,
    "Plex": 538,
    "Viddla": 539,
    "Elisa Viihde": 540,
    "rtve": 541,
    "filmfriend": 542,
    "CONTAR": 543,
    "Libreflix": 544,
    "Spuul": 545,
    "WOW Presents Plus": 546,
    "Alamo on Demand": 547,
    "IFFR Unleashed": 548,
    "IPLA": 549,
    "Tenk": 550,
    "Magellan TV": 551,
    "QFT Player": 552,
    "Telia Play": 553,
    "BroadwayHD": 554,
    "tvzavr": 556,
    "More TV": 557,
    "Cinépolis KLIC": 558,
    "Filmzie": 559,
    "Filmoteket": 560,
    "Lionsgate Play": 561,
    "MovieSaints": 562,
    "KPN": 563,
    "Filme Filme": 566,
    "True Story": 567,
    "DocAlliance Films": 569,
    "Premier": 570,
    "RTL Play": 572,
    "KinoPop": 573,
    "Oi Play": 574,
    "KoreaOnDemand": 575,
    "Klik Film": 576,
    "TvIgle": 577,
    "Strim": 578,
    "Film Movement Plus": 579,
    "Nova Play": 580,
    "iQIYI": 581,
    "Paramount+ Amazon Channel": 582,
    "MGM Plus Amazon Channel": 583,
    "Discovery Plus Amazon Channel": 584,
    "Metrograph": 585,
    "IFC Amazon Channel": 587,
    "MGM Amazon Channel": 588,
    "TELETOON+ Amazon Channel": 589,
    "Now TV Cinema": 591,
    "STV Player": 593,
    "Virgin TV Go": 594,
    "Eros Now Amazon Channel": 595,
    "Arrow Video Amazon Channel": 596,
    "Full Moon Amazon Channel": 597,
    "Pokémon Amazon Channel": 599,
    "Shout! Factory Amazon Channel": 600,
    "MotorTrend Amazon Channel": 601,
    "FilmBox Live Amazon Channel": 602,
    "CuriosityStream Amazon Channel": 603,
    "DocuBay Amazon Channel": 604,
    "Super Channel Amazon Channel": 605,
    "StackTV Amazon Channel": 606,
    "OUTtv Amazon Channel": 607,
    "Love Nature Amazon Channel": 608,
    "Smithsonian Channel Amazon Channel": 609,
    "BBC Earth Amazon Channel": 610,
    "UMC Amazon Channel": 612,
    "Freevee": 613,
    "VI movies and tv": 614,
    "W4free": 615,
    "HBO Max Free": 616,
    "Paus": 618,
    "Star Plus": 619,
    "DRTV": 620,
    "Dansk Filmskat": 621,
    "UPC TV": 622,
    "WeTV": 623,
    "KKTV": 624,
    "LINE TV": 625,
    "Otta": 626,
    "Voyo": 627,
    "Edisonline": 628,
    "OSN": 629,
    "STARZPLAY": 630,
    "HRTi": 631,
    "Showtime Roku Premium Channel": 632,
    "Paramount+ Roku Premium Channel": 633,
    "Starz Roku Premium Channel": 634,
    "AMC+ Roku Premium Channel": 635,
    "MGM Plus Roku Premium Channel": 636,
    "Pickbox NOW": 637,
    "Public Domain Movies": 638,
    "CineMember": 639,
    "Kino Now": 640,
    "Nexo Plus": 641,
    "STUDIOCANAL PRESENTS Apple TV Channel": 642,
    "Showtime Apple TV Channel": 675,
    "Eventive": 677,
    "Filmlegenden Amazon Channel": 678,
    "Cinema of Hearts Amazon Channel": 679,
    "Bloody Movies Amazon Channel": 680,
    "Film Total Amazon Channel": 681,
    "Looke Amazon Channel": 683,
    "FlixOlé Amazon Channel": 684,
    "OCS Amazon Channel ": 685,
    "Home of Horror Amazon Channel": 686,
    "Arthouse CNMA Amazon Channel": 687,
    "ShortsTV Amazon Channel": 688,
    "TVCortos Amazon Channel": 689,
    "Pongalo Amazon Channel  ": 690,
    "Play Suisse": 691,
    "Cultpix": 692,
    "Turk On Video Amazon Channel": 693,
    "meJane": 697,
    "FilmBox+": 701,
    "iBAKATV": 702,
    "IROKOTV": 704,
    "Hollywood Suite Amazon Channel": 705,
    "Moviedome Plus Amazon Channel": 706,
    "Aniverse Amazon Channel": 707,
    "Superfresh Amazon Channel": 708,
    "Comedy Central Plus Amazon Channel": 1706,
    "BluTV Amazon Channel": 1707,
    "GRJNGO Amazon Channel": 1709,
    "MTV Plus Amazon Channel": 1711,
    "RTL Passion Amazon Channel": 1712,
    "Silverline Amazon Channel": 1713,
    "Sony AXN Amazon Channel": 1714,
    "Shahid VIP": 1715,
    "Acontra Plus": 1717,
    "AVA VOBB": 1722,
    "AVA HBZ": 1723,
    "AVA CSAL": 1724,
    "AVA BGB": 1725,
    "Infinity Selection Amazon Channel": 1726,
    "CG Collection Amazon channel": 1727,
    "iWonder Full Amazon channel": 1728,
    "Full Action Amazon Channel": 1729,
    "Cine Comico Amazon Channel": 1730,
    "Universcine Amazon Channel": 1732,
    "Action Max Amazon Channel": 1733,
    "Filmo Amazon Channel": 1734,
    "Insomnia Amazon Channel": 1735,
    "Shadowz Amazon Channel": 1736,
    "INA  madelen Amazon Channel": 1737,
    "Benshi Amazon Channel": 1738,
    "Planet Horror Amazon Channel": 1740,
    "Dizi Amazon Channel": 1741,
    "Acontra Plus Amazon Channel": 1742,
    "Historia y Actualidad Amazon Channel": 1743,
    "Icon Film Amazon Channel": 1744,
    "Curzon Amazon Channel": 1745,
    "Hallmark TV Amazon Channel": 1746,
    "Studiocanal Presents Amazon Channel": 1747,
    "TOD": 1750,
    "filmingo": 1756,
    "Realeyz Amazon Channel": 1757,
    "Bet+": 1759,
    "Yorck on Demand": 1764,
    "ESPN Plus": 1768,
    "Paramount+ Showtime": 1770,
    "Takflix": 1771,
    "SkyShowtime": 1773,
    "Love and Passion Amazon Channel": 1788,
    "Lionsgate Plus": 1790,
    "Klassiki": 1793,
    "Starz Amazon Channel": 1794,
    "Netflix basic with Ads": 1796,
    "Studiocanal Presents MOVIECULT Amazon Channel": 1805,
    "Studiocanal Presents ALLSTARS Amazon Channel": 1806,
    "Cohen Media Amazon Channel": 1811,
    "HBO Max Amazon Channel": 1825,
    "Behind the Tree": 1829,
    "Popflick": 1832,
    "Tivify": 1838,
    "Britbox Apple TV Channel ": 1852,
    "Paramount Plus Apple TV Channel ": 1853,
    "AMC Plus Apple TV Channel ": 1854,
    "Starz Apple TV Channel": 1855,
    "Magenta TV": 1856,
    "Telenet": 1857,
    "Univer Video": 1860,
    "Filmow": 1861,
    "UAM TV": 1862,
    "Pass Warner Amazon Channel": 1870,
    "Runtime": 1875,
    "BrutX Amazon Channel": 1887,
    "Animation Digital Network Amazon Channel": 1888,
    "Universal+ Amazon Channel": 1889,
    "alleskino Amazon Channel": 1891,
    "RTL Crime Amazon Channel": 1892,
    "CineAutore Amazon Channel": 1894,
    "Anime Generation Amazon Channel": 1895,
    "Raro Video Amazon Channel": 1896,
    "MIDNIGHT FACTORY Amazon Channel": 1897,
    "Amazon miniTV": 1898,
    "ARD Plus": 1902
}

# Maps a country display name -> ISO 3166-1 alpha-2 region code.
COUNTRY_TO_REGION_CODE = {
    "Andorra": "AD",
    "United Arab Emirates": "AE",
    "Antigua and Barbuda": "AG",
    "Albania": "AL",
    "Argentina": "AR",
    "Austria": "AT",
    "Australia": "AU",
    "Bosnia and Herzegovina": "BA",
    "Barbados": "BB",
    "Belgium": "BE",
    "Bulgaria": "BG",
    "Bahrain": "BH",
    "Bermuda": "BM",
    "Bolivia": "BO",
    "Brazil": "BR",
    "Bahamas": "BS",
    "Canada": "CA",
    "Switzerland": "CH",
    "Cote D'Ivoire": "CI",
    "Chile": "CL",
    "Colombia": "CO",
    "Costa Rica": "CR",
    "Cuba": "CU",
    "Cape Verde": "CV",
    "Czech Republic": "CZ",
    "Germany": "DE",
    "Denmark": "DK",
    "Dominican Republic": "DO",
    "Algeria": "DZ",
    "Ecuador": "EC",
    "Estonia": "EE",
    "Egypt": "EG",
    "Spain": "ES",
    "Finland": "FI",
    "Fiji": "FJ",
    "France": "FR",
    "United Kingdom": "GB",
    "French Guiana": "GF",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Guadaloupe": "GP",
    "Equatorial Guinea": "GQ",
    "Greece": "GR",
    "Guatemala": "GT",
    "Hong Kong": "HK",
    "Honduras": "HN",
    "Croatia": "HR",
    "Hungary": "HU",
    "Indonesia": "ID",
    "Ireland": "IE",
    "Israel": "IL",
    "India": "IN",
    "Iraq": "IQ",
    "Iceland": "IS",
    "Italy": "IT",
    "Jamaica": "JM",
    "Jordan": "JO",
    "Japan": "JP",
    "Kenya": "KE",
    "South Korea": "KR",
    "Kuwait": "KW",
    "Lebanon": "LB",
    "St. Lucia": "LC",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Latvia": "LV",
    "Libyan Arab Jamahiriya": "LY",
    "Morocco": "MA",
    "Monaco": "MC",
    "Moldova": "MD",
    "Macedonia": "MK",
    "Malta": "MT",
    "Mauritius": "MU",
    "Mexico": "MX",
    "Malaysia": "MY",
    "Mozambique": "MZ",
    "Niger": "NE",
    "Nigeria": "NG",
    "Netherlands": "NL",
    "Norway": "NO",
    "New Zealand": "NZ",
    "Oman": "OM",
    "Panama": "PA",
    "Peru": "PE",
    "French Polynesia": "PF",
    "Philippines": "PH",
    "Pakistan": "PK",
    "Poland": "PL",
    "Palestinian Territory": "PS",
    "Portugal": "PT",
    "Paraguay": "PY",
    "Qatar": "QA",
    "Romania": "RO",
    "Serbia": "RS",
    "Russia": "RU",
    "Saudi Arabia": "SA",
    "Seychelles": "SC",
    "Sweden": "SE",
    "Singapore": "SG",
    "Slovenia": "SI",
    "Slovakia": "SK",
    "San Marino": "SM",
    "Senegal": "SN",
    "El Salvador": "SV",
    "Turks and Caicos Islands": "TC",
    "Thailand": "TH",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Trinidad and Tobago": "TT",
    "Taiwan": "TW",
    "Tanzania": "TZ",
    "Uganda": "UG",
    "United States of America": "US",
    "Uruguay": "UY",
    "Holy See": "VA",
    "Venezuela": "VE",
    "Kosovo": "XK",
    "Yemen": "YE",
    "South Africa": "ZA",
    "Zambia": "ZM"
}

# TMDB's fixed movie genre list (GET /genre/movie/list) — stable IDs, safe to
# hardcode. Used to translate /discover/movie's raw genre_ids into names so
# tmdb_fallback_search results match rag_search's List[str] genre shape.
GENRE_ID_TO_NAME = {
    28: "Action",
    12: "Adventure",
    16: "Animation",
    35: "Comedy",
    80: "Crime",
    99: "Documentary",
    18: "Drama",
    10751: "Family",
    14: "Fantasy",
    36: "History",
    27: "Horror",
    10402: "Music",
    9648: "Mystery",
    10749: "Romance",
    878: "Science Fiction",
    10770: "TV Movie",
    53: "Thriller",
    10752: "War",
    37: "Western",
}


# Case-insensitive index over PLATFORM_TO_PROVIDER_ID, built once at import.
_PLATFORM_TO_PROVIDER_ID_LOWER = {
    name.lower(): pid for name, pid in PLATFORM_TO_PROVIDER_ID.items()
}


def resolve_provider_ids(platforms: list[str]) -> list[int]:
    """Map platform display names to TMDB provider IDs, skipping unknowns.

    Case-insensitive, and consults PLATFORM_NAME_ALIASES for common alternate
    spellings (e.g. "Disney+") before giving up on a name.
    """
    ids, _unresolved = resolve_provider_ids_verbose(platforms)
    return ids


def resolve_provider_ids_verbose(platforms: list[str]) -> tuple[list[int], list[str]]:
    """Like resolve_provider_ids, but also returns names that couldn't be
    resolved to a TMDB provider ID at all — callers that need to warn (rather
    than silently drop) the filter should use this."""
    ids: list[int] = []
    unresolved: list[str] = []
    for name in platforms or []:
        lowered = name.strip().lower()
        pid = _PLATFORM_TO_PROVIDER_ID_LOWER.get(lowered)
        if pid is None:
            canonical = PLATFORM_NAME_ALIASES.get(lowered)
            if canonical:
                pid = PLATFORM_TO_PROVIDER_ID.get(canonical)
        if pid is not None:
            ids.append(pid)
        else:
            unresolved.append(name)
    return ids, unresolved


def resolve_region_code(country: str | None) -> str | None:
    """Map a country display name to an ISO region code.

    Accepts a display name (e.g. "Israel") or a raw 2-letter code (e.g. "IL").
    """
    if not country:
        return None
    if country in COUNTRY_TO_REGION_CODE:
        return COUNTRY_TO_REGION_CODE[country]
    if len(country) == 2:  # already looks like an ISO code
        return country.upper()
    return None


def resolve_genre_names(genre_ids: list[int]) -> list[str]:
    """Map TMDB genre IDs to names, skipping unknowns."""
    return [GENRE_ID_TO_NAME[g] for g in genre_ids or [] if g in GENRE_ID_TO_NAME]
